---

- name: ensure systemd unit for Linux
  template:
    src: consul.service.j2
    dest: /etc/systemd/system/consul.service
  register: systemd_unit_created
  when: "'Linux' in ansible_system"
  tags:
  - linux
  - systemd

- name: ensure systemd has loaded the config
  systemd:
    daemon_reload: yes
  when: "systemd_unit_created is changed"
  tags:
  - linux
  - systemd
