---
# tasks file for coffeesprout.consul

- name: ensure OS specifc vars are loaded for {{ ansible_os_family }}
  include_vars:
    file: "{{ ansible_os_family }}.yml"
  tags:
  - vars

- name: ensure depedencies are available
  package:
    name: "{{ consul_dependencies }}"
    state: present
  tags:
  - package
  - dependencies

- name: install Consul using package for Redhat
  include_tasks: RedHat_package.yml
  when:
  - "'RedHat' in ansible_os_family"
  - "'package' in consul_install_method" 

- name: install Consul using manual install
  include_tasks: manual_install.yml
  when:
  - "'manual' in consul_install_method" 

- name: ensure consul data and home directory
  file:
    path: "{{ item }}"
    state: directory
    recurse: True
    owner: consul
    group: consul
  with_items:
  - "{{ consul_data_dir }}"
  - "{{ consul_home }}"

- name: ensure consul configuration is present
  template:
    src: consul.hcl.j2
    dest: "{{ consul_home }}/consul.hcl"
    owner: consul
    group: consul

- name: ensure consul service is started for servers
  service:
    name: consul
    state: started
    enabled: True
  when: "'consul-servers' in group_names"

- name: ensure consul service is started on clients
  service:
    name: consul
    state: started
    enabled: True
  when: "'consul-clients' in group_names"
